# French main menu
[[main]]
name = "Services"
url = "#services"
weight = 2

[[main]]
name = "Équipe"
url = "#team"
weight = 3

[[main]]
name = "Partenaires"
url = "#customers"
weight = 4

[[main]]
name = "Portefeuille"
url = "portfolio/"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 6

[[main]]
name = "Vidéos"
url = "videos/"
weight = 7

[[main]]
name = "Contact"
url = "#contact"
weight = 8 