# French main menu
[[main]]
name = "Services"
url = "fr/#services"
weight = 2

[[main]]
name = "Équipe"
url = "fr/#team"
weight = 3

[[main]]
name = "Partenaires"
url = "fr/#customers"
weight = 4

[[main]]
name = "Portefeuille"
url = "fr/portfolio/"
weight = 5

[[main]]
name = "Blog"
url = "fr/blog/"
weight = 6

[[main]]
name = "Vidéos"
url = "fr/videos/"
weight = 7

[[main]]
name = "Contact"
url = "fr/#contact"
weight = 8 